### ISSUE TITLE
Iteration 1: Maintain Ride History

### ISSUE THREAD

**Issue by brianhhuynh38** [brianhhuynh38/PackTravel#3]
## Introduction

Currently, the system does not track the ride history of rides that are taken by users. This would be useful to determine what rides have existed in the past, acting as a sort of logging system viewable by users as a reference for fare cost changes over the course of time, especially for repeat destinations. This iteration could also be extended to include autocompletion of ride creation fields based on previous destinations.

This is a functionality that is specified under the "What's Next" section of the repository's ReadMe. This is probably a good starting point for becoming more familiar with the codebase and the database.

## Plans for This Iteration

- [x] Determine what database changes need to be made/appended in order to create a separate section for Ride Histories
- [x] **Backend Changes:**
    - [x] Create/Modify the Ride model(s) in order to be able to display them in at least 2 different contexts, pending and completed Rides
    - [x] Modify any existing files in order to be able to support the new models
    - [x] Set up the ability for a user or the system to designate when a ride is completed, if it does not exist already, and mark it as completed (or any other state that might be added)
- [x] **Frontend Changes:**
    - [x] Create a new page to be able to see a user's ride history (Likely a table display)
    - [x] _(Optional)_ Be able to autofill fields for requesting a new ride based on predictive reasoning based on past ride history (_ie. frequency of requests around a given timeframe_)
- [x] Create tests

**Comment by brianhhuynh38** [comment]
`ride_history` was successfully added as a database variable. This stores all the rides that a given user has taken or created

**Comment by brianhhuynh38** [comment]
The optional fronted change listed above is probably much more involved than simply a simple frontend change. I'll add this as a future implementation since it is practically a recommendation system.

**Comment by manavkamdar27** [comment]
The test case for checking ride history has been written and verified.

**Comment by manavkamdar27** [comment]
All the issues in this iteration have been resolved, closing it now
